/**
 * Returns a generator of the doms of the given tag name.
 * @param {string} tagName The tag name of the dom to create
 * @return {Function}
 */
export default function domGen(tagName) {

  /**
   * Generates a dom with the given params.
   * @param {object} [opts] The options to pass as the second arg of $('<tag/>', arg)
   * @param {object[]} args The objects to append to the element
   * @return {jQuery}
   */
  return (opts, ...args) => {
    if (!seemLikePlainObject(opts)) {
      args.unshift(opts)
      opts = undefined
    }

    return $('<' + tagName + '/>', opts).append(...[].concat(...args))
  }
}

/**
 * Checkes if the object is plain.
 * @param {object} o The object
 * @return {boolean}
 */
function seemLikePlainObject(o) {
  return o instanceof Object && Object.getPrototypeOf(o).hasOwnProperty('isPrototypeOf')
}
export const a = domGen('a')
export const abbr = domGen('abbr')
export const address = domGen('address')
export const area = domGen('area')
export const article = domGen('article')
export const aside = domGen('aside')
export const audio = domGen('audio')
export const b = domGen('b')
export const base = domGen('base')
export const bdi = domGen('bdi')
export const bdo = domGen('bdo')
export const blockquote = domGen('blockquote')
export const body = domGen('body')
export const br = domGen('br')
export const button = domGen('button')
export const canvas = domGen('canvas')
export const caption = domGen('caption')
export const cite = domGen('cite')
export const code = domGen('code')
export const col = domGen('col')
export const colgroup = domGen('colgroup')
export const data = domGen('data')
export const datalist = domGen('datalist')
export const dd = domGen('dd')
export const del = domGen('del')
export const details = domGen('details')
export const dfn = domGen('dfn')
export const dialog = domGen('dialog')
export const div = domGen('div')
export const dl = domGen('dl')
export const dt = domGen('dt')
export const em = domGen('em')
export const embed = domGen('embed')
export const fieldset = domGen('fieldset')
export const figcaption = domGen('figcaption')
export const figure = domGen('figure')
export const footer = domGen('footer')
export const form = domGen('form')
export const h1 = domGen('h1')
export const h2 = domGen('h2')
export const h3 = domGen('h3')
export const h4 = domGen('h4')
export const h5 = domGen('h5')
export const h6 = domGen('h6')
export const head = domGen('head')
export const header = domGen('header')
export const hr = domGen('hr')
export const html = domGen('html')
export const i = domGen('i')
export const iframe = domGen('iframe')
export const img = domGen('img')
export const input = domGen('input')
export const ins = domGen('ins')
export const kbd = domGen('kbd')
export const keygen = domGen('keygen')
export const label = domGen('label')
export const legend = domGen('legend')
export const li = domGen('li')
export const link = domGen('link')
export const main = domGen('main')
export const map = domGen('map')
export const mark = domGen('mark')
export const math = domGen('math')
export const menu = domGen('menu')
export const menuitem = domGen('menuitem')
export const meta = domGen('meta')
export const meter = domGen('meter')
export const nav = domGen('nav')
export const noscript = domGen('noscript')
export const object = domGen('object')
export const ol = domGen('ol')
export const optgroup = domGen('optgroup')
export const option = domGen('option')
export const output = domGen('output')
export const p = domGen('p')
export const param = domGen('param')
export const picture = domGen('picture')
export const pre = domGen('pre')
export const progress = domGen('progress')
export const q = domGen('q')
export const rb = domGen('rb')
export const rp = domGen('rp')
export const rt = domGen('rt')
export const rtc = domGen('rtc')
export const ruby = domGen('ruby')
export const s = domGen('s')
export const samp = domGen('samp')
export const script = domGen('script')
export const section = domGen('section')
export const select = domGen('select')
export const small = domGen('small')
export const source = domGen('source')
export const span = domGen('span')
export const strong = domGen('strong')
export const style = domGen('style')
export const sub = domGen('sub')
export const summary = domGen('summary')
export const sup = domGen('sup')
export const svg = domGen('svg')
export const table = domGen('table')
export const tbody = domGen('tbody')
export const td = domGen('td')
export const template = domGen('template')
export const textarea = domGen('textarea')
export const tfoot = domGen('tfoot')
export const th = domGen('th')
export const thead = domGen('thead')
export const time = domGen('time')
export const title = domGen('title')
export const tr = domGen('tr')
export const track = domGen('track')
export const u = domGen('u')
export const ul = domGen('ul')
export const video = domGen('video')
export const wbr = domGen('wbr')
